Move the commit, tag and push into the same job + increment the version at the beginning instead of at the end

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -16,96 +16,24 @@ on:
           - patch
 
 jobs:
-  set-version:
+  create-git-tag:
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.version.outputs.version }}
+      new_version: ${{ steps.increment_version.outputs.new_version }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
 
-      - name: Set version
-        id: version
+      - name: Increment version
+        id: increment_version
         run: |
-          echo "version=$(cat version.txt)" | tee -a $GITHUB_OUTPUT
-
-  create-git-tag:
-    needs:
-      - set-version
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4.1.1
-
-      - name: Create git tag
-        run: |
-          set -x
-          git config --local user.email "github-actions@comet.com"
-          git config --local user.name "github-actions"
-          git tag ${{needs.set-version.outputs.version}}
-          git push --no-verify origin ${{needs.set-version.outputs.version}}
-
-  release-apps:
-    needs:
-      - set-version
-      - create-git-tag
-    uses: ./.github/workflows/build_apps.yml
-    secrets: inherit
-    with:
-      version: ${{needs.set-version.outputs.version}}
-
-  release-sdk:
-    needs:
-      - set-version
-      - create-git-tag
-    uses: ./.github/workflows/build_and_publish_sdk.yaml
-    secrets: inherit
-    with:
-      version: ${{needs.set-version.outputs.version}}
-      is_release: true
-
-  publish-helm-chart:
-    needs:
-      - set-version
-      - create-git-tag
-    uses: ./.github/workflows/publish_helm_chart.yaml
-    secrets: inherit
-    with:
-      version: ${{needs.set-version.outputs.version}}
-
-  release-installer:
-    needs:
-      - set-version
-      - create-git-tag
-    uses: ./.github/workflows/build_and_publish_installer.yaml
-    secrets: inherit
-    with:
-      version: ${{needs.set-version.outputs.version}}
-      is_release: true
-
-  update_version_txt:
-    needs:
-      - set-version
-      - create-git-tag
-      - release-apps
-      - release-sdk
-      - publish-helm-chart
-      - release-installer
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4.1.1
-        with:
-          ref: main
-          fetch-depth: 0
-          token: ${{ secrets.GH_PAT_TO_ACCESS_GITHUB_API }}
-
-      - name: Bump version on main branch
-        id: update_version
-        shell: bash
-        run: |
-          set -x
+          echo "Incrementing version..."
           BASE_VERSION=$(cat version.txt)
+
+          if [[ ! "$BASE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version format: $BASE_VERSION"
+            exit 1
+          fi
 
           major_version=$(echo "$BASE_VERSION" | cut -d '.' -f 1)
           minor_version=$(echo "$BASE_VERSION" | cut -d '.' -f 2)
@@ -132,30 +60,70 @@ jobs:
           esac
 
           new_version="${major_version}.${minor_version}.${patch_version}"
-
-          # Update version file with the new version
-          echo "$new_version" > version.txt
           echo "new_version=${new_version}" >> $GITHUB_OUTPUT
 
+      - name: Update version.txt
+        run: |
+          echo "$new_version" > version.txt
+
       - name: Commit updated version file
-        shell: bash
         run: |
           git config --local user.email "github-actions@comet.com"
           git config --local user.name "github-actions"
           git add version.txt
-          git commit -m "Update base version to ${{steps.update_version.outputs.new_version}}"
-          echo "Version updated to ${{steps.update_version.outputs.new_version}} on main" >> $GITHUB_STEP_SUMMARY
+          git commit -m "Set version to ${{ steps.increment_version.outputs.new_version }}"
 
-      - name: Push changes
+      - name: Push new version.txt
         uses: ad-m/github-push-action@master
         with:
           github_token: ${{ secrets.GH_PAT_TO_ACCESS_GITHUB_API }}
           branch: ${{ github.ref }}
           force_with_lease: true
 
+      - name: Create git tag
+        run: |
+          set -x
+          git config --local user.email "github-actions@comet.com"
+          git config --local user.name "github-actions"
+          git tag ${{ steps.increment_version.outputs.new_version }}
+          git push --no-verify origin ${{ steps.increment_version.outputs.new_version }}
+
+  release-apps:
+    needs:
+      - create-git-tag
+    uses: ./.github/workflows/build_apps.yml
+    secrets: inherit
+    with:
+      version: ${{ needs.create-git-tag.outputs.new_version }}
+
+  release-sdk:
+    needs:
+      - create-git-tag
+    uses: ./.github/workflows/build_and_publish_sdk.yml
+    secrets: inherit
+    with:
+      version: ${{ needs.create-git-tag.outputs.new_version }}
+      is_release: true
+
+  publish-helm-chart:
+    needs:
+      - create-git-tag
+    uses: ./.github/workflows/publish_helm_chart.yaml
+    secrets: inherit
+    with:
+      version: ${{ needs.create-git-tag.outputs.new_version }}
+
+  release-installer:
+    needs:
+      - create-git-tag
+    uses: ./.github/workflows/build_and_publish_installer.yaml
+    secrets: inherit
+    with:
+      version: ${{ needs.create-git-tag.outputs.new_version }}
+      is_release: true
+
   create-github-release:
     needs:
-      - set-version
       - create-git-tag
     runs-on: ubuntu-latest
     steps:
@@ -169,6 +137,6 @@ jobs:
       - name: Create GitHub release
         uses: mikepenz/action-gh-release@v0.4.1
         with:
-          tag_name: ${{needs.set-version.outputs.version}}
-          body: ${{steps.release_changelog.outputs.changelog}}
+          tag_name: ${{ needs.create-git-tag.outputs.new_version }}
+          body: ${{ steps.release_changelog.outputs.changelog }}
           generate_release_notes: true
