adjust wait

diff --git a/.github/workflows/test_installer.yml b/.github/workflows/test_installer.yml
--- a/.github/workflows/test_installer.yml
+++ b/.github/workflows/test_installer.yml
@@ -1,6 +1,10 @@
 name: Install Local Version of Opik
 
 on:
+    push:
+        branches:
+            - andrei/basic_installer_workflow
+
     workflow_dispatch:
 
 jobs:
@@ -31,8 +35,31 @@ jobs:
                 cd deployment/docker-compose
                 docker compose up --detach
 
-            - name: Wait
-              run: sleep 5
+            - name: Check Docker pods are up
+              run: |
+                cd deployment/docker-compose
+                max_retries=5
+                wait_interval=3
+                retries=0
+
+                while [[ $retries -lt $max_retries]]; do
+                    containers=$(docker compose ps --status running -q)
+                    if [ -z "$containers" ]; then
+                        echo "Waiting for containers to be up... (Attempt: $((retries+1))/$max_retries)"
+                        sleep $wait_interval
+                        retries=$((retries+1))
+                    else
+                        echo "Containers running"
+                        docker compose ps
+                        break
+                    fi
+                done
+
+                if [[ $retries -eq $max_retries ]]; then
+                    echo "Containers failed to start"
+                    docker compose ps
+                    exit 1
+                fi
 
             - name: Check app is up via the UI
               run: |
